### ISSUE TITLE
Compiling bins

### ISSUE THREAD

**Issue by TheArchKnight** [Serasidis/STM32_HID_Bootloader#10]
Hi, i had been trying to compile teh bins on Linux. Exactly the F1 bins. This is what it throws
`In file included from Src/main.c:31:
Inc/config.h:121:3: error: #error "No config for this target"
  #error "No config for this target"
 `
Any idea?

**Comment by Serasidis** [comment]
That means you have not selected a target board.
Select any of the following make commands:
```
make maple-mini
make generic-pc13
make generic-pd2
make generic-pd1
make generic-pa1
make generic-pb9
make generic-pe2
make generic-pa9
make generic-pe5
make generic-pb7
make generic-pb0
make generic-pb12
make mini-stm32v3
