### ISSUE TITLE
Please add instructions in case the user reaches this repository (no need to compile)

### ISSUE THREAD

**Issue by rtek1000** [Serasidis/STM32_HID_Bootloader#11]
Hello, 

Please add instructions in case the user reaches this repository.

- User does not need to compile anything

- Simply apply the path on the Arduino_STM32 folder and write the bootloader in STM32 (which is in the bootloader_only_binaries folder), maybe using stlink (STSW-LINK004 etc) or via serial port (demonstrator - UM0462 etc).

- The first time the bootloader does not generate a serial port, only after the IDE upload some sketch. Then the user must select this serial port (added in the IDE) to upload again.

Thank you.

![hid bootloader](https://user-images.githubusercontent.com/8660811/56453707-b6e1db80-631c-11e9-8294-5ce30676ec44.jpg)

**Comment by Serasidis** [comment]
Thanks !

**Comment by Serasidis** [comment]
The **STM32 HID Bootloader** is available on the Official [Arduino_Core_STM32](https://github.com/stm32duino/Arduino_Core_STM32) Core
