### ISSUE TITLE
STM Official Core Support

### ISSUE THREAD

**Issue by wanders78746** [Serasidis/STM32_HID_Bootloader#18]
I apologize in advance, as I am a n00b just getting started in STM32duino development, but I've decided to use the STM Official Core. Will there be support for it soon? THANKS for the impressive work so far!

**Comment by fpistm** [comment]
This is already supported. 😉

**Comment by wanders78746** [comment]
Sorry, it wasn't clear from the descriptioni. Thanks! Nothing like a 2K bootloader that doesn't need a driver in Windows.

**Comment by fpistm** [comment]
No worry ;)
Here a note by @Serasidis in the Wiki:
https://github.com/stm32duino/wiki/wiki/Upload-methods#hid-bootloader-22-hid-bl

**Comment by Andy2No** [comment]
The Readme page still says 
> 8. STM Official Core will be supported soon.

Is that just an out of date comment?  See:

https://github.com/Serasidis/STM32_HID_Bootloader/blob/master/README.md

**Comment by Serasidis** [comment]
Out of date information has been removed from README.md file
