### ISSUE TITLE
Link to Arduino IDE patch file for Roger core no longer works

### ISSUE THREAD

**Issue by raghur** [Serasidis/STM32_HID_Bootloader#20]
> Apply the Arduino_STM32_patch from here in case of using Roger's Core (select the zip file according to your Operating System).

Link to patch is broken... I got it from github history - but is there a reason to not provide it/support it?

**Comment by Serasidis** [comment]
Version 2.1.0 includes the patch files for Win, Linux and MacOS

https://github.com/Serasidis/STM32_HID_Bootloader/releases/tag/2.1.0

**Comment by raghur** [comment]
I picked them up from git history... but I don't understand why they were deleted in the first place?

**Comment by Serasidis** [comment]
It is better to separate the source code from the binary files. Those who just want to program the Bootloader do not need to download the source code.

**Comment by raghur** [comment]
I understand... perhaps you can host it on Gdrive or something and link to it from the README if you don't expect source changes to the IDE patch. 

Feel free to close the issue.
