### ISSUE TITLE
USB device not recognized

### ISSUE THREAD

**Issue by dmkng** [Serasidis/STM32_HID_Bootloader#51]
Hello,
I flashed the hid_generic_pc13.bin file to my BluePill board using a serial dongle and STM32CubeProgrammer with the default start address (0x08000000) and also the start address specified in README (0x8000000). When plugging in the board via USB the LED doesn't blink or anything, and after 1 second I'm getting a Windows notification "USB device not recognized". Of course I can't flash anything using Arduino IDE because hid-flash can't find any HID device.
It is not the board's fault because STM32duino bootloader works perfectly, LED flashes when plugged in after flashing via serial dongle and I can successfully flash sketches via USB. What can be the problem? Please help. Thanks.

**Comment by bance** [comment]
same fault here with 2.2.1 and 2.2.2

bootloader flashed with st-link v2. verified ok.

**Comment by dmkng** [comment]
I discovered what's wrong. Typical Blue Pill board uses STM32F103C6T6 (32MB RAM, 10MB Flash) but this bootloader supports only STM32F103C8T6 (64MB RAM, 20MB Flash), I created a fork where I roughly fixed this issue creating new target "bluepill" but I think that it can be fixed in some better way than what I did. Here's my fork: https://github.com/dmkng/STM32_HID_Bootloader

**Comment by bance** [comment]
thank you for the solution, dmkng!

**Comment by Istria1704** [comment]
Thank you!
I had the identical problem. USB Device not recognized/malfunctioned. Also with a cheap aliexpress STM32F103C**6**T6 board. After a couple of hours of searching around and experimenting, it turned out to be this. 

Can conform the @dmkng fork is the fix for STM32F103C6T6 boards.

Thanks a lot!
